ERROR: failed to solve: failed to prepare extraction snapshot "extract-398956704---R5 sha256:d57a3df7a3c5a0b5a448ebe8184217d8502a0345fe698b8462ade4064aebdf57": parent snapshot sha256:daf3d3d9c0fcfc396decf55acb0da7079456723d8edffdde83dfa1ba0e84b136 does not exist: not found

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/a2iocx4wk4d2oz1vm5jwrsw42
Traceback (most recent call last):
  File "/app/test_wrapper.py", line 44, in <module>
    code_tester()
  File "/app/test_wrapper.py", line 25, in code_tester
    module = importlib.import_module(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/app/answer_1742998073.py", line 1, in <module>
    dsjkflsgfjldfjhg
NameError: name 'dsjkflsgfjldfjhg' is not defined
Incorrect for input: [1], received: 1, expected: [1]
All tests passed!
All tests passed!
